### ISSUE TITLE
Pygments issues

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#201]
I'm still running into lots of issues with pygments. In an experiment to fix, I replaced it with rouge.

https://github.com/ropensci/roweb/commit/d320e75666b60e435a22ce83a9f8556dd637407f

but that now breaks the blog post previews:

![image](https://cloud.githubusercontent.com/assets/138494/9892447/a997d25e-5bc3-11e5-89fd-5c5b0032977e.png)

Investigating with @sckott

**Comment by karthik** [comment]
Nokogiri simply doesn't work for me.

```
 jekyll serve --watch
WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/karthik/Documents/work/Github/ropensci/roweb/_config.yml
/Users/karthik/Documents/work/Github/ropensci/roweb/_plugins/remove_alerts.rb:5:in `require': cannot load such file -- nokogiri (LoadError)
	from /Users/karthik/Documents/work/Github/ropensci/roweb/_plugins/remove_alerts.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:74:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:73:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:72:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/site.rb:79:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/site.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:29:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.1/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by cboettig** [comment]
ruby gems are a mess, I vaguely remember hitting this issue a while back.  I've found this is a case where dockerizing really does make a difference; I think you should be able to build locally with this image: https://hub.docker.com/r/ropensci/roweb  

(that dockerfile builds on the ruby 2.1 libraries, I haven't tried moving to 2.2; from what I recall upgrading frequently breaks things where jekyll is concerned so I appreciate docker's way of sidestepping that)...

**Comment by sckott** [comment]
does that work when doing `bundle jekyll serve`
